version: 0.2

phases:
  build:
    commands:
      - echo "Deploying Brain Tasks App to EKS..."
      # Update kubeconfig so kubectl can talk to your cluster
      - aws eks --region ap-south-1 update-kubeconfig --name brain-tasks-cluster
      # Apply Kubernetes manifests
      - kubectl apply -f deployment.yml
      - kubectl apply -f service.yml
